
mysql -u root -pKikakuka.01 < create_db.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  grant_privileges.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  tbsecurity_status.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  tbsecurity_user.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  tbsecurity_role.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  tbsecurity_menu.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  tbsecurity_module.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  tbsecurity_rolemodule.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  tbsecurity_usermodule.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  tbsecurity_userrole.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_apply_userrole.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_delete_menu.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_delete_module.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_delete_rolemodule.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_delete_role.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_delete_usermodule.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_delete_user.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_get_assignedroles.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_get_availableroles.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_get_menulist.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_get_modulelist.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_get_rolelist.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_get_rolemodulelist.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_get_statuslist.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_get_userlist.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_get_usermodulelist.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_get_userrights.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_get_user.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_insert_menu.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_insert_module.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_insert_rolemodule.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_insert_role.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_insert_usermodule.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_insert_user.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_update_menu.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_update_module.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_update_rolemodule.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_update_role.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_update_usermodule.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  spsecurity_update_user.sql
mysql -u root -pKikakuka.01 soccer_plus_db <  vwsecurity_get_userrights.sql

